# Generated by Django 4.2.1 on 2023-06-12 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Texte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('preambule', models.TextField(blank=True, null=True)),
                ('numero_de_loi', models.CharField(max_length=50)),
                ('adoption', models.DateField()),
            ],
        ),
    ]
