# Generated by Django 4.2.1 on 2023-06-12 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseisjLaw', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapitre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(max_length=200)),
                ('libelle', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Livre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(max_length=200)),
                ('libelle', models.CharField(max_length=200, unique=True)),
                ('text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseisjLaw.texte')),
            ],
            options={
                'ordering': ['libelle'],
            },
        ),
        migrations.CreateModel(
            name='Titre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(max_length=200)),
                ('libelle', models.CharField(max_length=200, unique=True)),
                ('livre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='baseisjLaw.livre')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(max_length=200)),
                ('libelle', models.CharField(max_length=200)),
                ('chapitre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseisjLaw.chapitre')),
            ],
        ),
        migrations.AddField(
            model_name='chapitre',
            name='titre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseisjLaw.titre'),
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(max_length=200)),
                ('libelle', models.CharField(max_length=200)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseisjLaw.section')),
            ],
        ),
        migrations.CreateModel(
            name='Alinea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(max_length=200)),
                ('libelle', models.TextField()),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseisjLaw.article')),
            ],
        ),
    ]
