# Generated by Django 4.2.1 on 2023-05-24 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basefinale', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fichier',
            old_name='upload',
            new_name='upload_date',
        ),
    ]
