# Generated by Django 4.2.1 on 2023-05-24 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basefinale', '0005_alter_employe_matricule'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichier',
            name='content',
            field=models.FileField(null=True, upload_to='public'),
        ),
    ]
